language: python
python:
   - 3.6
   - 3.7

install:
    - pip install -e .

before_script:
    - pip install -r requirements.txt

script:
   - py.test tests/run_tests.py

after_success:
   - coveralls

notifications:
   email: false
