language:
   - python

python:
   - 3.6
   - 3.7

addons:
  apt:
    packages:
    - python-vtk

install:
   - pip install -U pip
   - pip install pytest pytest-pep8 pytest-cov python-coveralls
     #- pip install mayavi
     #- pip install pep8

script:
   - py.test tests/run_tests.py --cov src

after_success:
   - coveralls

notifications:
   email: false
